app:
  baseUrl: https://backstage-demo-deployment.herokuapp.com

backend:
  baseUrl: https://backstage-demo-deployment.herokuapp.com
  listen:
    port: 
      $env: PORT

auth:
  environment: production
