app:
  title: Backstage Demo
  baseUrl: http://localhost:7000

organization:
  name: Backstage

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: sqlite3
    connection: ':memory:'


integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
auth:
  environment: development
  providers:
    github:
      development:
        clientId:
          $env: GITHUB_DEVELOPMENT_CLIENT_ID
        clientSecret:
          $env: GITHUB_DEVELOPMENT_CLIENT_SECRET
      production:
        clientId:
          $env: GITHUB_PRODUCTION_CLIENT_ID
        clientSecret:
          $env: GITHUB_PRODUCTION_CLIENT_SECRET

catalog:
  rules:
    - allow: [Component, API, Location]
  locations:
    # Backstage example components
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Backstage example APIs
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # The backstage demo deployment (this)
    - type: url
      target: https://github.com/backstage/demo/blob/master/catalog-info.yaml

    # The backstage library repository
    - type: url
      target: https://github.com/backstage/backstage/blob/master/catalog-info.yaml

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers
